# Generated by Django 4.2.11 on 2026-01-13 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('region', models.CharField(max_length=200, verbose_name='区划')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='部门')),
                ('requester', models.CharField(blank=True, max_length=100, null=True, verbose_name='需求提出人')),
                ('request_date', models.DateField(verbose_name='需求提出日期')),
                ('issue_type', models.CharField(choices=[('implementation', '实施定制'), ('data_issue', '数据问题'), ('user_consultation', '用户咨询'), ('new_feature', '新增功能'), ('program_issue', '程序问题'), ('simple_training', '简单培训')], max_length=50, verbose_name='问题类型')),
                ('functional_module', models.CharField(blank=True, max_length=200, null=True, verbose_name='功能模块')),
                ('issue_description', models.TextField(verbose_name='问题描述')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('assistant', models.CharField(blank=True, max_length=200, null=True, verbose_name='协助人')),
                ('processing_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='处理耗时（总）')),
                ('expected_completion_time', models.DateField(blank=True, null=True, verbose_name='预计完成时间')),
                ('completion_status', models.CharField(choices=[('completed', '已完成'), ('in_progress', '处理中'), ('pending', '待处理'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='完成情况')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '运维记录',
                'verbose_name_plural': '运维记录',
                'db_table': 'maintenance_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
