# Generated by Django 4.2.11 on 2026-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='issue_type',
            field=models.CharField(choices=[('user_consultation', '用户咨询'), ('new_feature', '新增功能'), ('program_issue', '程序问题'), ('implementation', '实施定制'), ('data_issue', '数据问题'), ('statistics', '统计类'), ('simple_training', '简单培训'), ('troubleshooting', '故障排查'), ('technical_support', '技术支持'), ('account_issue', '账号问题'), ('other', '其他')], max_length=50, verbose_name='问题类型'),
        ),
    ]
