# Generated by Django 4.2.11 on 2026-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_add_task_needs_modification_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfig',
            name='api_params',
            field=models.TextField(blank=True, help_text='JSON格式的接口参数模板，使用{phone}、{content}等占位符。例如：{"phoneNum": "{phone}", "mesConent": "{content}", "regionCode": "371000000000", "source": "oms"}。如果不配置，将使用默认值：phoneNum和mesConent为动态值，regionCode固定为371000000000，source固定为oms', null=True, verbose_name='接口参数模板'),
        ),
    ]
