# Generated by Django 4.2.11 on 2025-11-21 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assistant_employees',
            field=models.ManyToManyField(blank=True, related_name='assisted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='协助员工'),
        ),
    ]
