# Generated by Django 4.2.11 on 2025-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('reviewed', '已审核'), ('assigned', '已指派'), ('in_progress', '处理中'), ('completed', '已完成'), ('confirmed', '已确认'), ('closed', '已结单')], default='pending_review', max_length=20, verbose_name='状态'),
        ),
    ]
