# Generated by Django 4.2.11 on 2025-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('problem', '问题'), ('requirement', '需求')], max_length=20, null=True, verbose_name='任务类型'),
        ),
    ]
